// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    $.stellar();
    return $('#contact').submit(function(e) {
      var email, message, name;
      e.preventDefault();
      name = $('input[name="name"]').val();
      email = $('input[name="email"]').val();
      message = $('textarea[name="message"]').val();
      if (!(!!name && !!email && !!message)) {
        return noty({
          text: 'please fill in necessary fields',
          type: 'error'
        });
      } else {
        return $.ajax({
          url: 'http://localhost:8080/api/contacts',
          type: 'POST',
          data: {
            name: name,
            email: email,
            message: message
          },
          dataType: 'json',
          success: function(data, textStatus, XHR) {
            return noty({
              text: 'Message sent successfully! We will contact you shorty',
              type: 'success'
            });
          },
          error: function(XHR, textStatus, error) {
            return noty({
              text: 'Something is wrong, please try again',
              type: 'error'
            });
          }
        });
      }
    });
  });

}).call(this);

//# sourceMappingURL=custom.map
